//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drive.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttendanceID { get; set; }
        public int AttendanceEmployee { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public System.TimeSpan AttendanceTime { get; set; }
        public int AttendanceDuration { get; set; }
        public int AttendanceResult { get; set; }
        public string AttendanceComment { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Request Request { get; set; }
        public virtual Result Result { get; set; }
    }
}
