//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drive.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlackList
    {
        public int BlackListID { get; set; }
        public string BlackListDescription { get; set; }
    
        public virtual Visitor Visitor { get; set; }
    }
}
