//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ОООАдмиралтейские_Верфи.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestID { get; set; }
        public System.DateTime RequestDateAdd { get; set; }
        public System.DateTime RequestDateStart { get; set; }
        public System.DateTime RequestDateEnd { get; set; }
        public int RequestSubdivision { get; set; }
        public string RequestPurpose { get; set; }
        public int RequestVisitor { get; set; }
        public int RequestStatus { get; set; }
        public string RequestReason { get; set; }
    
        public virtual Attendance Attendance { get; set; }
        public virtual Status Status { get; set; }
        public virtual Subdivision Subdivision { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
